// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) 
	{
		int n = Integer.parseInt(args[0]);
		int bigger = 0;
		int sOrE = 0;
		double random;
		double ratio;
		for (int i = 0; i<n; i++)
		{
			random = Math.random();
			if (random>0.5) 
			{
				bigger++;
			}
			else
			{
				sOrE++;
			}
		}
		System.out.println("> 0.5: " + bigger + " times");
		System.out.println("<= 0.5: " + sOrE + " times");
		if (sOrE != 0) 
		{
			ratio = (double)bigger / sOrE;
			System.out.println("Ratio: " + ratio);
		}
	}
}
